# Generated by Django 4.2.3 on 2023-07-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
