# Generated by Django 4.2.1 on 2023-07-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_contact_emailus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
